In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/transactions.csv")

In [3]:
df.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,$-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
1,7475328,2010-01-01 00:02:00,561,4575,$14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN
2,7475329,2010-01-01 00:02:00,1129,102,$80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,NaN
3,7475331,2010-01-01 00:05:00,430,2860,$200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,NaN
4,7475332,2010-01-01 00:06:00,848,3915,$46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,NaN

In [4]:
df.shape

(13305915, 12)

In [6]:
df_small = df.sample(
    n=50000,
    random_state=42
)

In [8]:
df_small.info()

<class 'pandas.DataFrame'>
Index: 50000 entries, 3714287 to 5478562
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              50000 non-null  int64
 1   date            50000 non-null  str
 2   client_id       50000 non-null  int64
 3   card_id         50000 non-null  int64
 4   amount          50000 non-null  str
 5   use_chip        50000 non-null  str
 6   merchant_id     50000 non-null  int64
 7   merchant_city   50000 non-null  str
 8   merchant_state  44198 non-null  str
 9   zip             43852 non-null  float64
 10  mcc             50000 non-null  int64
 11  errors          781 non-null    str
dtypes: float64(1), int64(5), str(6)
memory usage: 5.0 MB

In [9]:
df_small.isnull().sum()

id                    0
date                  0
client_id             0
card_id               0
amount                0
use_chip              0
merchant_id           0
merchant_city         0
merchant_state     5802
zip                6148
mcc                   0
errors            49219
dtype: int64

In [10]:
df_small.describe()

,id,client_id,card_id,merchant_id,zip,mcc
count,5.000000e+04,50000.00000,50000.000000,50000.000000,43852.000000,50000.000000
mean,1.556779e+07,1026.90272,3472.553060,47741.471000,51319.559997,5564.131840
std,4.701586e+06,583.63988,1675.848333,25870.837722,29371.239076,869.044464
min,7.476006e+06,0.00000,0.000000,22.000000,1040.000000,1711.000000
25%,1.149275e+07,519.00000,2412.000000,25857.000000,28602.000000,5300.000000
50%,1.554593e+07,1075.00000,3587.000000,45926.000000,47465.000000,5499.000000
75%,1.964969e+07,1533.00000,4913.250000,67570.000000,78130.000000,5812.000000
max,2.376140e+07,1998.00000,6138.000000,100340.000000,99687.000000,9402.000000

In [11]:
df_small.describe(include='object')

C:\Users\JAGDISH\AppData\Local\Temp\ipykernel_10692\3337266068.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_small.describe(include='object')

,date,amount,use_chip,merchant_city,merchant_state,errors
count,50000,50000,50000,50000,44198,781
unique,49670,13079,3,3860,104,8
top,2018-11-07 09:24:00,$80.00,Swipe Transaction,ONLINE,CA,Insufficient Balance
freq,3,502,26224,5802,5386,489

In [12]:
# Save the sampled dataset
df_small.to_csv("sampled_dataset_50000.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!